const Generation = require('../models/Generation');
const projectService = require('./projectService');

/**
 * Export all generations for a project in a given format
 */

const exportAsMarkdown = async (projectId, userId) => {
  const project = await projectService.getProjectById(projectId, userId);
  const generations = await Generation.find({ projectId, userId }).sort({ createdAt: -1 });

  let md = `# Test Cases — ${project.projectName}\n\n`;
  md += `> Generated by AI Test Case Generator\n\n`;

  if (project.description) {
    md += `**Description:** ${project.description}\n\n`;
  }

  md += `---\n\n`;

  for (let i = 0; i < generations.length; i++) {
    const gen = generations[i];
    md += `## ${i + 1}. ${gen.goal}\n\n`;
    md += `- **Types:** ${(gen.testTypes || []).join(', ')}\n`;
    md += `- **Model:** ${gen.modelUsed || 'N/A'}\n`;
    md += `- **Feedback:** ${gen.feedback || 'none'}\n`;
    md += `- **Generated:** ${new Date(gen.createdAt).toLocaleString()}\n\n`;
    md += `\`\`\`javascript\n${gen.generatedContent}\n\`\`\`\n\n`;
    md += `---\n\n`;
  }

  return { content: md, filename: `${project.projectName.replace(/\s+/g, '_')}_tests.md` };
};

const exportAsJSON = async (projectId, userId) => {
  const project = await projectService.getProjectById(projectId, userId);
  const generations = await Generation.find({ projectId, userId }).sort({ createdAt: -1 });

  const data = {
    project: {
      name: project.projectName,
      description: project.description,
      technologies: project.detectedTechnologies?.map((t) => t.name) || [],
    },
    generatedAt: new Date().toISOString(),
    totalTests: generations.length,
    tests: generations.map((gen) => ({
      goal: gen.goal,
      testTypes: gen.testTypes,
      model: gen.modelUsed,
      feedback: gen.feedback,
      qualityScore: gen.qualityScore,
      content: gen.generatedContent,
      createdAt: gen.createdAt,
    })),
  };

  return {
    content: JSON.stringify(data, null, 2),
    filename: `${project.projectName.replace(/\s+/g, '_')}_tests.json`,
  };
};

const exportAsText = async (projectId, userId) => {
  const project = await projectService.getProjectById(projectId, userId);
  const generations = await Generation.find({ projectId, userId }).sort({ createdAt: -1 });

  let text = `TEST CASES — ${project.projectName.toUpperCase()}\n`;
  text += `${'='.repeat(60)}\n\n`;

  for (let i = 0; i < generations.length; i++) {
    const gen = generations[i];
    text += `[${i + 1}] ${gen.goal}\n`;
    text += `Types: ${(gen.testTypes || []).join(', ')} | Model: ${gen.modelUsed || 'N/A'}\n`;
    text += `${'-'.repeat(40)}\n`;
    text += `${gen.generatedContent}\n\n`;
    text += `${'='.repeat(60)}\n\n`;
  }

  return {
    content: text,
    filename: `${project.projectName.replace(/\s+/g, '_')}_tests.txt`,
  };
};

module.exports = { exportAsMarkdown, exportAsJSON, exportAsText };
